version: '2.1'

services:
  terraform-example-app1:
    image: terraform-example-app1
    build: ./app1
    environment:
      NODE_ENV: production
      APP2URI: terraform-example-app2:3000
    ports:
      - 80:3000
    ## set your startup file here
    command: npm start
  
  terraform-example-app2:
    image: terraform-example-app2
    build: ./app2
    environment:
      NODE_ENV: production
    ports:
      - 8080:3000
    ## set your startup file here
    command: npm start